#!/bin/bash

# download & modify two required python3 libraries

path=~/Downloads

lp_nephirus=https://launchpad.net/~nephirus/+archive/ubuntu
lp_jacob=https://launchpad.net/~jacob/+archive/ubuntu

pkg_num=2

declare -A pkgs

# Modify both below packages (python3-gpg & python3-libvirt) to change the
# "Depends" clause to python3.7 (>= 3.7~) rather than python3 (>= 3.7~) as
# this allows these packages to used with Python 3.7 installed from a PPA

pkgs[1,0]="$lp_nephirus/ppa-gnupg/+files"
pkgs[1,1]="python3-gpg_1.13.0-2ubuntu3"
pkgs[1,2]="python3-gpg_1.13.0-2ubuntu3~16.04.sav0"

pkgs[2,0]="$lp_jacob/virtualisation/+files"
pkgs[2,1]="python3-libvirt_5.5.0-0~19.04~ppa0"
pkgs[2,2]="python3-libvirt_5.5.0-0~19.04~sav0"

pushd $path >/dev/null || exit

kern=$(dpkg --print-architecture)

for (( i = 1; i <= $pkg_num; i++ )) do

  pkg_src=${pkgs[$i,1]}_$kern
  pkg_mod=${pkgs[$i,2]}_$kern

  # no good if patch doesn't exist
  if [ ! -e $pkg_src.patch ]; then break; fi

  # get source package from pool
  rm $pkg_src.deb
  wget ${pkgs[$i,0]}/$pkg_src.deb

  # extract source package
  dpkg-deb -R $pkg_src.deb $pkg_src

  # patch source package
  patch -p1 < $pkg_src.patch

  # rename as modded package
  if [ ! "$pkg_src" = "$pkg_mod" ]; then mv $pkg_src $pkg_mod; fi

  # pack modded package & cleanup
  fakeroot dpkg-deb -b $pkg_mod
  rm -R $pkg_mod

done
popd >/dev/null

# now do some additional upgrades

pushd /etc/apt/sources.list.d >/dev/null

# install Python 3.7.4 from ppa:deadsnakes/ppa
sudo apt-get install python3.7 python3.7-dev

# add new alternative for Python 3.7 (return Python 3.6 to be current default,
# use "sudo update-alternatives --config python3" to change if ever required)
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 3
sudo update-alternatives -set python3 /usr/bin/python3.6

# latest NTFS-3G
sudo add-apt-repository -y ppa:anton+/miscellaneous

# upgrade libva*1.7* libraries (Video Acceleration)
sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
# latest ffmpeg 4 (Bionic), VLC 3 & dependencies
sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
sudo add-apt-repository -y ppa:jonathonf/vlc-3
# latest ffmpeg 4 (Xenial + Bionic) & dependencies
sudo add-apt-repository -y ppa:sergey-dryabzhinsky/ffmpeg

# various useful package upgrades
#sudo add-apt-repository -y ppa:sergey-dryabzhinsky/packages

# GnuPG 2.2.17 (latest 2019-07-09) -- requires various Disco libraries before upgrading
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5158D7C3EE4ADC1A6D7326760F19EF517DFDA048
echo "deb http://ppa.launchpad.net/nephirus/ppa-gnupg/ubuntu disco main" | sudo tee nephirus-ppa-gnupg-disco.list
echo "deb-src http://ppa.launchpad.net/nephirus/ppa-gnupg/ubuntu disco main" | sudo tee -a nephirus-ppa-gnupg-disco.list

# QEMU 4.0 -- requires various other standard Disco libraries before upgrading
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F90C8262A258CC539FD64268A6128A6CCDFBABD4
echo "deb http://ppa.launchpad.net/jacob/virtualisation/ubuntu disco main" | sudo tee jacob-virtualisation-disco.list
echo "deb-src http://ppa.launchpad.net/jacob/virtualisation/ubuntu disco main" | sudo tee -a jacob-virtualisation-disco.list

popd >/dev/null

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
sudo apt-get install ntfs-3g ffmpeg

pushd /var/cache/apt/archives >/dev/null
# install two modded Python packages to satisfy Disco dependencies
for (( i = 1; i <= 2; i++ )) do
  deb=${pkgs[$i,2]}_$kern.deb
  sudo cp -p "$path/$deb" . && sudo chown root:root $deb
  sudo dpkg -i "$deb"
done
popd >/dev/null

# create symbolic links to Python 3.6 from two (python3-gpg & python3-libvirt)
# Python 3.7 object libraries as this means these newer Python3 libraries that
# require Python 3.7 will still (based on some amount of testing!) work fine
find /usr/lib/python3/dist-packages -name \*37m\* -type f -print0 | while IFS= read -r -d '' file; do
  sudo ln -s $file ${file//37m/36m}
done

