#!/bin/bash

pushd /etc/apt/sources.list.d >/dev/null

# latest NTFS-3G
sudo add-apt-repository -y ppa:anton+/miscellaneous

# latest ffmpeg (v4.x) & dependencies
sudo add-apt-repository -y ppa:sergey-dryabzhinsky/ffmpeg

# various useful package upgrades
sudo add-apt-repository -y ppa:sergey-dryabzhinsky/packages

# GnuPG 2.2.17 (latest 2019-07-09) -- requires numerous Disco+ libraries before upgrading
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5158D7C3EE4ADC1A6D7326760F19EF517DFDA048
echo "deb http://ppa.launchpad.net/nephirus/ppa-gnupg/ubuntu disco main" | sudo tee nephirus-ppa-gnupg-disco.list
echo "deb-src http://ppa.launchpad.net/nephirus/ppa-gnupg/ubuntu disco main" | sudo tee -a nephirus-ppa-gnupg-disco.list

# QEMU 4.0 -- requires numerous Disco+ libraries before upgrading
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F90C8262A258CC539FD64268A6128A6CCDFBABD4
echo "deb http://ppa.launchpad.net/jacob/virtualisation/ubuntu disco main" | sudo tee jacob-virtualisation-disco.list
echo "deb-src http://ppa.launchpad.net/jacob/virtualisation/ubuntu disco main" | sudo tee -a jacob-virtualisation-disco.list

popd >/dev/null

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
sudo apt-get install ntfs-3g ffmpeg

