#!/bin/bash

# latest NTFS-3G
sudo add-apt-repository -y ppa:anton+/miscellaneous

# latest ffmpeg (v4.x) & dependencies
sudo add-apt-repository -y ppa:sergey-dryabzhinsky/ffmpeg

# various useful package upgrades
sudo add-apt-repository -y ppa:sergey-dryabzhinsky/packages

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
sudo apt-get install ntfs-3g ffmpeg

