#!/bin/bash

SIGNKEY=$DEBSIGN

SERIES=xenial
PACKAGE=ubuntu-enhanced
VERSION=0.4-2sav0

EXTRA_REPOS=""

ALT_BUILD=N
SRC_BUILD=N
BUILDINFO=N

BUILD_TGZ=~/pbuilder/$SERIES-base.tgz

. ~/.local/bin/pbuilder-all
