#!/bin/bash

SIGNKEY=$DEBSIGN

SERIES=xenial
PACKAGE=xenial-enhanced
VERSION=0.3-1sav0

EXTRA_REPOS=""

ALT_BUILD=N
SRC_BUILD=N
BUILDINFO=N

BUILD_TGZ=~/pbuilder/$SERIES-base.tgz

. ~/.local/bin/pbuilder-all
